name: resource_browser
description: A Flutter web app to browse and view videos, PDFs, markdown, and MHTML files.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # For making HTTP requests to fetch files
  http: ^1.1.0
  
  # For rendering markdown files (updated package)
  flutter_markdown_plus: ^1.0.5
  
  # For video playback
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true